version: "3.9"

services:
  mongodb:
    image: mongo:6
    container_name: securekyc_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: securekyc_backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/
      - EMAIL_ADDRESS=${EMAIL_ADDRESS}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: securekyc_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true

volumes:
  mongo_data:
